# 全局配置-异步模式配置
logging.async.enabled=true      # 启动异步模式
logging.async.queue_size=8192   # 缓存队列大小
logging.async.policy=overrun    # 缓存溢出的处理策略, overrun: 循环覆盖, block: 阻塞
logging.async.thread_num=1      # 异步线程池大小

# 日志模块配置, 默认情况下第一个日志模块作为default logger
logging.logger.main=info,console,rotating   # 格式：logging.logger.<日志模块>=<最低输出日志等级>,<Sink模块1>,[Sink模块2,...]
#logging.logger.module1=warn,console,daily   # 格式：logging.logger.<日志模块>=<最低输出日志等级>,<Sink模块1>,[Sink模块2,...]

# 控制台sink配置
logging.sink.console.type=console   # 格式：logging.sink.<Sink模块>.type=<console|rotating|daily>

# 滚动文件sink配置
logging.sink.rotating.type=rotating
logging.sink.rotating.file_name=/home/robot/resource/log/robot/files_upload_mgr.log
#logging.sink.rotating.max_size=10485760     # 可选项, 默认为10MB
#logging.sink.rotating.max_files=10          # 可选项, 默认为10

# 每日文件sink配置
#logging.sink.daily.type=daily
#logging.sink.daily.file_name=/home/robot/resource/log/robot/daily.log
#logging.sink.daily.max_files=10     # 可选项, 默认为10
#logging.sink.daily.hour=0          # 可选项, 默认为0
#logging.sink.daily.minute=0        # 可选项, 默认为0